#!/bin/bash
#
# Print the run log: every job submitted through submit.sh, with what SLURM says happened.
#
#   bash scripts/runlog.sh                 # everything on record
#   bash scripts/runlog.sh --since 2026-08-01
#   bash scripts/runlog.sh --md > RUNLOG.md
#
# WHY THIS IS GENERATED, NOT WRITTEN. A hand-kept list of commands is wrong the first time
# somebody runs one at a shell prompt instead of from the notebook — and a run log that is
# only sometimes right is worse than none, because it gets trusted. Two sources, both
# automatic, joined on job id:
#
#   logs/submissions.tsv   submit.sh appends one row per submission — the ARGUMENTS
#   sacct                  SLURM's own accounting — the OUTCOME (state, exit, elapsed, MaxRSS)
#
# Neither is sufficient alone: sacct does not record --export values and ages out after the
# cluster's retention window; submissions.tsv does not know whether the job worked.
#
# Jobs NOT submitted through submit.sh (a bare sbatch, or the notebook's sbatch_on_biowulf)
# appear with a blank args column but are still listed, because sacct sees them regardless.
# That is deliberate: the log should show what actually ran, not what was supposed to.

set -uo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUBLOG="${PROJECT_ROOT}/logs/submissions.tsv"

SINCE="2026-01-01"
FORMAT="text"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --since) SINCE="$2"; shift 2 ;;
        --md)    FORMAT="md"; shift ;;
        -h|--help) sed -n '2,26p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

if ! command -v sacct >/dev/null 2>&1; then
    echo "sacct not found — run this on the cluster." >&2
    exit 1
fi

# One row per job (not per job step): -X collapses .batch/.extern children.
SACCT=$(sacct --starttime "$SINCE" --user "${USER}" -X --parsable2 --noheader \
        --format=JobID,JobName,State,ExitCode,Elapsed,ReqCPUS,ReqMem,MaxRSS,Partition 2>/dev/null)

awk -v FMT="$FORMAT" -v SUB="$SUBLOG" -F'|' '
    BEGIN {
        while ((getline line < SUB) > 0) {
            n = split(line, f, "\t")
            if (f[2] == "jobid") continue                  # header
            when[f[2]] = f[1]; args[f[2]] = f[5]; exp[f[2]] = f[6]; who[f[2]] = f[7]
        }
        if (FMT == "md") {
            print "# Run log"
            print ""
            print "Generated by `scripts/runlog.sh` — do not edit by hand."
            print ""
            print "| submitted (UTC) | job | name | state | elapsed | cpus | mem req | max RSS | args |"
            print "|---|---|---|---|---|---|---|---|---|"
        } else {
            printf "%-20s %-10s %-30s %-14s %10s %5s %9s %10s  %s\n",
                   "SUBMITTED (UTC)", "JOB", "NAME", "STATE", "ELAPSED", "CPUS", "REQMEM", "MAXRSS", "ARGS"
        }
    }
    {
        id=$1; name=$2; state=$3; exitc=$4; elapsed=$5; cpus=$6; reqmem=$7; maxrss=$8
        if (maxrss == "") maxrss = "-"
        st = state; if (exitc != "0:0" && exitc != "") st = state " (" exitc ")"
        t = (id in when) ? when[id] : "-"
        a = (id in args) ? args[id] : ""
        if (FMT == "md")
            printf "| %s | %s | `%s` | %s | %s | %s | %s | %s | `%s` |\n",
                   t, id, name, st, elapsed, cpus, reqmem, maxrss, a
        else
            printf "%-20s %-10s %-30s %-14s %10s %5s %9s %10s  %s\n",
                   t, id, name, st, elapsed, cpus, reqmem, maxrss, a
    }
' <<< "$SACCT"

if [[ ! -f "$SUBLOG" ]]; then
    echo >&2
    echo "note: no ${SUBLOG#$PROJECT_ROOT/} yet — argument columns will be blank until" >&2
    echo "      jobs are submitted through ./submit.sh." >&2
fi
